server:
  port: 8080

spring:
  application:
    name: hello-devops

app:
  version: 1.0.0
  environment: ${APP_ENVIRONMENT:local}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always